Repository dask/distributed, pull requests merged in 2022-09, with the labels that each got.

#6985 Revert "Fix co-assignment for binary operations"
  distributed/scheduler.py
  distributed/tests/test_scheduler.py
Labels: performance, regression, memory

#7041 Minor tweaks to Sphinx documentation
  distributed/client.py
  distributed/nanny.py
  distributed/worker_state_machine.py
  docs/source/scheduling-policies.rst
Labels: documentation

#7018 Detect mismatching Python version in scheduler
  distributed/tests/test_versions.py
  distributed/versions.py
Labels: bug

#7072 AMM support for actors
  distributed/active_memory_manager.py
  distributed/deploy/adaptive.py
  distributed/scheduler.py
  distributed/tests/test_active_memory_manager.py
  distributed/worker_state_machine.py
  docs/source/actors.rst
Labels: memory

#7042 Enable Active Memory Manager by default
  distributed/client.py
  distributed/distributed.yaml
  distributed/protocol/tests/test_serialize.py
  distributed/tests/test_active_memory_manager.py
  distributed/tests/test_actor.py
  distributed/tests/test_client.py
  distributed/tests/test_failed_workers.py
  distributed/tests/test_resources.py
  distributed/tests/test_scheduler.py
  distributed/tests/test_semaphore.py
  distributed/tests/test_steal.py
  distributed/tests/test_stories.py
  distributed/tests/test_stress.py
  distributed/tests/test_tls_functional.py
  distributed/tests/test_worker.py
  distributed/tests/test_worker_memory.py
  distributed/tests/test_worker_state_machine.py
  distributed/utils_test.py
  docs/source/active_memory_manager.rst
  docs/source/resilience.rst
Labels: memory
