Repository dask/distributed, pull requests merged in 2023-06, with the labels that each got.

#7874 Dashboard: Fix Fine Performance Metrics w/ Bokeh 3
  distributed/dashboard/components/scheduler.py
Labels: needs review

#7879 Enforce dtypes in P2P shuffle
  distributed/shuffle/_arrow.py
  distributed/shuffle/_merge.py
  distributed/shuffle/_scheduler_extension.py
  distributed/shuffle/_shuffle.py
  distributed/shuffle/_worker_extension.py
  distributed/shuffle/tests/test_shuffle.py
Labels: shuffle

#7811 add a timeout to client.as_completed that mirrors concurrent.futures.as_completed's timeout
  distributed/client.py
  distributed/tests/test_as_completed.py
Labels: needs review

#7467 avoid calls to make_current() and make_clear() by using asyncio.run in LoopRunner
  distributed/actor.py
  distributed/deploy/cluster.py
  distributed/deploy/spec.py
  distributed/deploy/tests/test_adaptive.py
  distributed/deploy/tests/test_cluster.py
  distributed/deploy/tests/test_spec_cluster.py
  distributed/tests/test_actor.py
  distributed/tests/test_client.py
  distributed/tests/test_client_loop.py
  distributed/tests/test_utils.py
  distributed/utils.py
Labels: needs review

#7897 Improve memory footprint of P2P rechunking
  distributed/shuffle/_rechunk.py
  distributed/shuffle/_scheduler_extension.py
  distributed/shuffle/_shuffle.py
  distributed/shuffle/_worker_extension.py
  distributed/shuffle/tests/test_rechunk.py
Labels: needs review, shuffle

#7938 Add idle time to fine performance metrics
  distributed/dashboard/components/scheduler.py
  distributed/dashboard/tests/test_scheduler_bokeh.py
  distributed/itertools.py
  distributed/scheduler.py
  distributed/spans.py
  distributed/tests/test_itertools.py
  distributed/tests/test_spans.py
Labels: diagnostics

#7935 Fix annotations and spans leaking between threads
  distributed/client.py
  distributed/spans.py
Labels: skip-caching
